_format_version: "3.0"

services:
  - name: auth-service
    # url: http://172.18.0.4:8080
    url: http://auth-service:8080
    routes:
      - name: auth-route
        paths:
          - /api/v1/auth
        strip_path: false
  
  - name: user-service
    # url: http://172.18.0.5:8090
    url: http://user-service:8090
    routes:
      - name: user-route
        paths:
          - /api/v1/users
        strip_path: false

  - name: expense-service
    url: http://expense-service:8070
    routes:
      - name: expense-route
        paths:
          - /api/v1/expenses
        strip_path: false

  - name: data-science-service
    url: http://data-science-service:8010
    routes:
      - name: data-science-route
        paths:
          - /api/v1/ds
        strip_path: false